config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                      root GET    /                                                                                        dashboards#index
#                     rooms GET    /rooms(.:format)                                                                         rooms#index
#                           POST   /rooms(.:format)                                                                         rooms#create
#                  new_room GET    /rooms/new(.:format)                                                                     rooms#new
#                 edit_room GET    /rooms/:id/edit(.:format)                                                                rooms#edit
#                      room GET    /rooms/:id(.:format)                                                                     rooms#show
#                           PATCH  /rooms/:id(.:format)                                                                     rooms#update
#                           PUT    /rooms/:id(.:format)                                                                     rooms#update
#                           DELETE /rooms/:id(.:format)                                                                     rooms#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :rooms
  resources :users
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @rooms = Room.all
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/index.html.erb
<div class="app-content content">
  <div class="content-wrapper">

    <div class="content-body">
      <!-- Base style table -->
      <section id="base-style">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title float-left">
                  All Rooms
                </h4>
                <div class="float-right">
                  <%=link_to new_room_path,  class: "btn btn-sm btn-danger box-shadow-2 btn-min-width pull-right white" do%>
                    <i class="ft-plus white"></i>Add New Room
                  <%end%>
                </div>
              </div>
              <div class="card-body mt-1">
                <div class="table-responsive">
                  <table id="active-accounts" class="table alt-pagination table-wrapper">
                    <thead>
                      <tr>
                        <th class="border-top-0">#</th>
                        <th class="border-top-0">Full Address</th>
                        <th class="border-top-0">Price</th>
                        <th class="border-top-0">Size</th>
                        <th class="border-top-0">Condition</th>
                        <th class="border-top-0">Create at</th>
                        <th class="border-top-0">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <%@rooms.each_with_index do |room, index|%>
                        <tr>
                          <td>
                            <%=index + 1%>
                          </td>
                          <td>
                            <div class="ac-type"><%=room.full_address%></div>
                          </td>
                          <td>
                            <div class="ac-number"><%=room.room_price%></div>
                          </td>
                          <td>
                            <div class="ac-hol-name"><%=room.room_size%></div>
                          </td>
                          <td>
                            <div class="ac-status badge badge-success badge-pill badge-sm"><%=room.room_condition%>
                            </div>
                          </td>
                          <td>
                            <div class="ac-balance">
                              <%=room.created_at.strftime("%d/%m/%Y")%>
                            </div>
                          </td>
                          <td>
                            <div class="action">
                              <%=link_to edit_room_path(room) do%>
                                <i class="la la-pencil-square success"></i>
                              <%end%>
                              <%=link_to room, :method => :delete, data: { confirm: "Are you sure?" } do%>
                                <i class="la la-trash danger"></i>
                              <%end%>
                              <%=link_to root_path do%>
                                <i class="la la-eye secondary"></i>
                              <%end%>
                            </div>
                          </td>
                        </tr>
                      <%end%>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>